title: Master's block
author: Guram Bregadze
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Your chance to learn more
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  MasterGuram # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
